### PR TITLE
Missing props from LiveChatLoaderContext to messenger provider

### PR DESCRIPTION
**Pull request by FateXRebirth**
## Description

Requiring additional props from `LiveChat LoaderContext` in `useChat`, and use it to load messenger provider

## Related Issue

N/A

## Motivation and Context

N/A

## How Has This Been Tested?

I have tested it on my own project, using chrome developer tools to check if the correct version of Customer Chat SDK is downloaded or not

## Screenshots (if appropriate):
N/A

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FateXRebirth** [comment]
@michaeldijkstra please take a look this PR when you are available, This PR try to find missing props in preload phase of messenger provider.

**Comment by michaeldijkstra** [comment]
@FateXRebirth Sorry about this! I assume this dropped the `appId`?

Change looks good. Will merge and do a release for you.

**Comment by FateXRebirth** [comment]
@michaeldijkstra thanks for rapid response and deploy in advance.

Yes, `appID` and `locale`, I also want to adjust documentation a bit, Let user knows where they should pass `appID`, I will create another commit to update that, please help me check it out.

**Comment by michaeldijkstra** [comment]
> I will create another commit to update that, please help me check it out.

@FateXRebirth Update looks good. If you're finished with changes I'll merge and release this.

**Comment by FateXRebirth** [comment]
@michaeldijkstra I done, please help me deploy it, thank you 👍

**Comment by michaeldijkstra** [comment]
@FateXRebirth This has been merged and released as 2.0.5 🚀

**Pull request merged**
