### PR TITLE
Update `module` target in .babelrc

### PR DESCRIPTION
**Pull request by altaywtf**
a tiny PR to fix https://github.com/calibreapp/react-live-chat-loader/pull/329#issuecomment-1817315959.

btw you don't need `@babel/plugin-proposal-class-properties` and `@babel/plugin-proposal-object-rest-spread` because they're are merged into `preset-env`.

1. https://babeljs.io/docs/babel-plugin-transform-class-properties
2. https://babeljs.io/docs/babel-plugin-transform-object-rest-spread

you're also using `nullish coalescing operator` but didn't have to add a transform for that, guess why? because it's also a part of the `preset-env`: https://babeljs.io/docs/babel-plugin-transform-nullish-coalescing-operator 😇👍

### CODE REVIEW

**Comment by robmorieson** [comment]
@altaywtf thanks for spotting the bug and rolling out a fix: very much appreciated 🙌 

Re. the additional points: would you be happy to include them in this PR?

**Comment by altaywtf** [comment]
sure thing, all good for me!

**Review by robmorieson — APPROVED** [review]
Looks good to go, thanks @altaywtf 🙏

**Comment by altaywtf** [comment]
🎉 🎉 😅 looking forward to eliminating one more line here: 

```js
// webpack.common.js
exclude: createTranspileDependencies([
  'react-live-chat-loader',
  'p-timeout',
  'p-min-delay',
]),
```

**Pull request merged**
