### PR TITLE
add support for HubSpot

### PR DESCRIPTION
**Pull request by drwlrsn**
👋🏻 Hi there! 
- [ ] remove logging

## What does this PR introduce?
- adds a HubSpot Provider
- I found HS can take awhile to load, so I added the ability to include a spinner
## Screenshots
chat-widget-loading

### CODE REVIEW

**Comment by benschwarz** [comment]
Hey @drwlrsn, thanks for your contribution. If you merge `main` branch the vercel deployment should complete successfully.

**Comment by mariuszkosmatka** [comment]
Hi @drwlrsn 👋 has this work been abandoned? We're looking at using react-live-chat-loader with HubSpot too, so this PR would be quite useful to us too.

**Comment by drwlrsn** [comment]
Hey! @mariuszkosmatka the company I was working for when I whipped this up no longer exists and so neither does the need for it. But, I'm sure we can get this over the line. You might end up being the first (again) using it in production.

**Comment by cmbritten** [comment]
Hi @drwlrsn -- I'd love to be able to make use of this too!  Thanks for your work here.  I'll be following to see if it gets merged.

**Comment by jucallej** [comment]
Following this work on https://github.com/calibreapp/react-live-chat-loader/pull/281 as I don't have permissions to push to that fork. Let me know if I'm missing something

**Pull request merged**
