### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by elmoeleven**
## Comments:
Hey folks. 

I added types. I had made a `react-live-chat-loader.d.ts` for our own project and just decided to move the whole shebang. 

I also added husky & lint-staged for developer quality of life. 

## Changelog: 
- a4a3f0b Move components to from js to ts.
- 4775a0b Move LiveChatLoaderProvider into components.
- a4a14c0 Move hooks from js to ts.
- 03e024d Move providers from js to ts.
- ee23948 Move index from js to ts.
- 664a2bf Add types, nix states.
- d92c237 Add eslintrc.json.
- ac83510 Add tsconfig, update .babelrc.
- 644b2e8 Packages.

### CODE REVIEW

**Comment by elmoeleven** [comment]
Hey folks, any movement on this? Any questions, comments or concerns?

**Comment by benschwarz** [comment]
Hey @elmoeleven, sorry I forgot to post a message when this came in 🙈 

I want TS on all of our projects and this is one of the outliers! Thanks for your contribution.

We'll review and let you know.

**Comment by mikedijkstra** [comment]
@elmoeleven thanks for updating this with Userlike. We’re going to review your PR this week so we can get it merged in!

**Comment by mikedijkstra** [comment]
@elmoeleven Thanks again for putting together this PR. As it's a bigger move for the project (moving to Typescript) I want to make sure we setup the right conventions, so I've put together some broad-stroke feedback I'd like to address first and then I can run it and just make sure everything still works as expected.

- The general consensus is that React.FC or React.FunctionComponent is discouraged (see [react typescript cheatsheet](https://github.com/typescript-cheatsheets/react#function-components)) so let's remove those from our functional components.
- I noticed the constants got removed and changed to strings. I'd prefer to keep them as constants to prevent any typo errors. Perhaps we should re-implement them as Typescript enums?
- I don't see any benefit to prefixing interfaces with `I` and it has potential downsides. So let's remove those e.g. `IIntercomProps` should be `IntercomProps`
- I think we should co-locate interfaces/types where we can (such as where they're only used in a single component). So let's move the widget specific props into their files e.g. `HelpScoutIcon` and `HelpScoutProps` can be moved into `HelpScout/index.tsx`

I'm happy to discuss any of these feedback points 🙂

**Comment by elmoeleven** [comment]
Hey @mikedijkstra, all sounds fair.

- FWIW, we use `React.FC` _because of the pitfalls_ listed in the cheatsheet, but, your house your rules, I'll update it 😄.
- I created a type union for them, which provides you the safety of ensuring that there are no typos and still provides write time type-checking. Is there a reason for the state abstraction to be preserved in the compiled code?
- Will amend.
- Will amend.

The updates should land _soon_. Thanks again for the review!

**Comment by elmoeleven** [comment]
@mikedijkstra updates have been pushed.

Still waiting on your response here for this: 
> I created a type union for them, which provides you the safety of ensuring that there are no typos and still provides write time type-checking. Is there a reason for the state abstraction to be preserved in the compiled code?

I've removed `React.FC` in favour of `JSX.Element | null`, let me know if you'd prefer a different type.

Outside of that let me know if you spot anything else that needs amending.

**Comment by mikedijkstra** [comment]
> I created a type union for them, which provides you the safety of ensuring that there are no typos and still provides write time type-checking. Is there a reason for the state abstraction to be preserved in the compiled code?

It's my preference for autocompletion during development, but I can see typescript will validate the state so happy to keep it how you've implemented it.

> I've removed React.FC in favour of JSX.Element | null, let me know if you'd prefer a different type.

:+1:

> Outside of that let me know if you spot anything else that needs amending.

I noticed a some `I` prefixes are still present e.g. `IDriftProps`, `IUserLikeProps`

The only other request we have is to remove `husky` and `lint-staged`. We've had issues with this across our team in the past and we'll look at using actions to enforce linting at the PR level.

**Comment by elmoeleven** [comment]
@mikedijkstra I've removed the extra Is, and gotten rid of `husky` & `lint-staged`. Thanks again for the review.

**Comment by elmoeleven** [comment]
Hey, just following up here. Anything else to be done for us to see this merged?

**Comment by mikedijkstra** [comment]
@all-contributors please add @elmoeleven for code

**Pull request merged**
